package com.kobie.engine.processing

import org.homeage.transaction.TransactionDTO;
import org.homeage.web.dto.AccountDTO;

rule "Base Campaign"
    when
    	acct : AccountDTO( canEarn == true, portfolioId == 35 )  
    	tran : TransactionDTO (type in ("SALE", "RETURN"), category in ("INSTORE", "ONLINE"))
    	resp : ProcessResponse()
    then
    	System.out.println("The account can earn and portfolio ID is " + acct.getPortfolioId());
    	resp.setWasSuccessful(true);
end